device: cuda:0

epochs: 100

loss:
  name: BCELoss
  params: {}

optimizer:
  name: Adam
  params:
    lr: 0.0001

metrics:
  ExactMatchAccuracy:
    num_labels: 14
  MultiLabelAUROC:
    num_labels: 14
  F1Score:
    num_labels: 14

# early_stopper:
#   patience: 10
#   delta: 0.001

# profiler:
#   project: "pytorch-template"
#   name: "SqueezeViT_3_no_aug"

checkpointer:
  save_dir: "/workspace/data/torchmanager/checkpoints/finalexp_ab2"
  save_period: 5
  # resume: true
  # resume_path: "/workspace/data/torchmanager/checkpoints/testexp1/epoch_20.pth"