dataset_common_config:
  import_type: "torchvision"
  dataset_name: "CIFAR10"
  root: "/home/karan/Documents/GitHub/BTP/torchmanager/data"
  download: true

dataset_split_config:
  train:
    train: true
  test:
    train: false

split_ratios:
  val:
    parent: "train"
    ratio: 0.2


transforms_config:
  train:
    ToTensor: {}
  val:
    ToTensor: {}
  test:
    ToTensor: {}


data_loader_config:
  train:
    batch_size: 64
    shuffle: true
    num_workers: 0
    pin_memory: true
  val:
    batch_size: 128
    shuffle: false
    num_workers: 0
    pin_memory: true
  test:
    batch_size: 128
    shuffle: false
    num_workers: 0
    pin_memory: true
