dataset_common_config:
  import_type: "torchvision"
  dataset_name: "CIFAR10"
  root: "D:\\Work\\College\\Classroom\\torchmanager\\data"
  download: true

dataset_split_config:
  train:
    train: true
  test:
    train: false

split_ratios:
  val:
    parent: "train"
    ratio: 0.2


transforms_config:
  train:
    RandomCrop:
      size: 32
      padding: 4
    RandomHorizontalFlip:
      p: 0.5
    ToTensor: {}
    Normalize:
      mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.2023
      - 0.1994
      - 0.2010
  val:
    ToTensor: {}
    Normalize:
      mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.2023
      - 0.1994
      - 0.2010
  test:
    ToTensor: {}
    Normalize:
      mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.2023
      - 0.1994
      - 0.2010



data_loader_config:
  train:
    batch_size: 64
    shuffle: true
    num_workers: 0
    pin_memory: true
  val:
    batch_size: 128
    shuffle: false
    num_workers: 0
    pin_memory: true
  test:
    batch_size: 128
    shuffle: false
    num_workers: 0
    pin_memory: true
